using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TurnManager : MonoBehaviour
{
    private static TurnManager instance;
    [SerializeField] private PlayerTurn playerOne;
    [SerializeField] private PlayerTurn playerTwo;
    [SerializeField] private float timeBetweenTurns;

    //Cameras
    [SerializeField] private Camera Camera1;
    [SerializeField] private Camera Camera2;

    private int currentPlayerIndex;
    private bool waitingForNextTurn;
    private float turnDelay;

    private void Awake()
    {
        if (instance == null)
        {
            instance = this;
            currentPlayerIndex = 1;
            playerOne.SetPlayerTurn(1);
            playerTwo.SetPlayerTurn(2);
        }
    }

    private void Update()
    {
        if (waitingForNextTurn)
        {
            turnDelay += Time.deltaTime;
            if (turnDelay >= timeBetweenTurns)
            {
                turnDelay = 0;
                waitingForNextTurn = false;
                ChangeTurn();
            }
        }
    }

    public bool IsItPlayerTurn(int index)
    {
        if (waitingForNextTurn)
        {
            return true;
        }
        return index == currentPlayerIndex;
    }

    public static TurnManager GetInstance()
    {
        return instance;
    }

    public void TriggerChangeTurn()
    {
        waitingForNextTurn = true;
    }


    private void ChangeTurn()
    {
        Debug.Log("Swapping turns)");
        if (currentPlayerIndex == 1)
        {
            currentPlayerIndex = 2;
            Camera1.depth = -1;
            Camera2.depth = 1;

        }
        else if (currentPlayerIndex == 2)
        {
            currentPlayerIndex = 1;
            Camera2.depth = -1;
            Camera1.depth = 1;
        }
    }
}
